site_name: 免费的AI工具箱
theme:
  name: material
  custom_dir: material/overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    primary: green
    toggle:
      icon: material/link
      name: Switch to light mode
  extra:
    homepage: https://freeaitool.com
  features:
    - navigation.instant
    - navigation.tabs
  font:
    text: Roboto
    code: Roboto Mono

copyright: Copyright &copy; 2016 - 2023 Free AI Tool 

markdown_extensions: 
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags
  - social:
      cards_layout: default
  - blog:
      post_slugify_separator: _
      path: blog
      permalink: blog/{slug}.html
      rss: rss.xml
      limit: 5
      feed_description: Free AI Tool Blog
      feed_image: images/logo.png
      feed_author: Kevin
      feed_author_email:
      categories_allowed:
        - 提示词
        - 知识
        - 图像
        - AI助手

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kevinzjpeng/freeaitool
  blog:
    dir: blog
    author: Kevin Peng
    author_image: https://avatars.githubusercontent.com/u/1113470
    words_read_per_minute: 300
    list_length: 25
    extended_preview: true
  generator: false
  analytics:
    provider: google
    property: G-H9VGEGXRSK
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/heart
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/heart-broken
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! How could this page be improved?

nav:
  - 首页: index.md
  - 博客:
    - blog/index.md
    