site_name: 免费的AI工具箱
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    primary: green
    toggle:
      icon: material/link
      name: Switch to light mode
  custom_dir: overrides
  extra:
    homepage: https://freeaitool.com
  features:
    - navigation.instant
    - navigation.tabs
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags
  - social:
      cards_layout: default
  - blog:
      post_slugify_separator: _
      path: blog
      permalink: blog/{slug}.html
      rss: rss.xml
      limit: 5
      feed_description: My Docs Blog
      feed_image: images/logo.png
      feed_author: My Docs
      feed_author_email:

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kevinzjpeng/freeaitool

nav:
  - Home: index.md
  - 博客:
    - blog/index.md
  - 工具:
    - blog/index.md